name: netify_dio
description: Dio adapter for Netify network inspector. Beautiful in-app debugging for Dio HTTP client.
version: 3.0.3
homepage: https://netify.dev
repository: https://github.com/netify-app/netify-flutter
issue_tracker: https://github.com/netify-app/netify-flutter/issues
documentation: https://netify.dev/docs/dio

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  netify_core: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
