name: netify_http
description: HTTP adapter for Netify network inspector. Beautiful in-app debugging for dart:io http package.
version: 3.0.0
homepage: https://netify.dev
repository: https://github.com/netify-app/netify-flutter
issue_tracker: https://github.com/netify-app/netify-flutter/issues
documentation: https://netify.dev/docs/http

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  netify_core:
    path: ../netify_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
