name: netify_http
description: HTTP (dart:io) adapter for Netify network inspector
version: 3.0.0
homepage: https://github.com/ricoerlan/netify

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  netify_core:
    path: ../netify_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
